server:
  port: 3001
  domain: http://localhost
  version: 1.0.0

logging: #日志级别
  level:
    ROOT: INFO
        
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#  redis:
#    enabled: true
#    database: 11
#    host: 127.0.0.1
#    port: 6379
#    password: ryJy6J0L
#    pool:
#      maxActive: 8  # 连接池最大连接数（使用负值表示没有限制）
#      maxWait: 800 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      maxIdle: 8 # 连接池中的最大空闲连接
#      minIdle: 2 # 连接池中的最小空闲连接
#    timeout: 2000 # 连接或读取超时时长（毫秒）

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
      
mybatis:
  dbType: mysql
  typeAliasesPackage: com.muzhu.**.entity
  dbMapperLocations:
    mysql: classpath*:com/muzhu/**/mapper/mysql/*Mapper.xml
    oracle: classpath*:com/muzhu/**/mapper/oracle/*Mapper.xml      

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
user:
   username: 炮进
   age: 60
   gender: 栅栏